### ISSUE TITLE
Why would you rip off a simple library?

### ISSUE THREAD

**Issue by glennposadas** [ugurethemaydin/SwiftConfettiView#1]
I sent you an email, someone opened a ticket: https://github.com/sudeepag/SAConfettiView/issues/57

**Comment by ugurethemaydin** [comment]
Unfortunately, this library has not been updated for a long time and does not work after swift 4.2.
If you get an error and cannot use this library, you can visit it.
For the active repo and many new features,

https://github.com/ugurethemaydin/SwiftConfettiView

**Comment by nathfreder** [comment]
dude

**Comment by nathfreder** [comment]
not cool

**Comment by lewis-smith** [comment]
I appreciate you taking the time to update this library, but you should def credit the original work. 

Apart from bring rude and reflecting badly on you personally, this kind of behaviour really opens you up to legal action which is definitely not worth it for just adding the proper attribution.
