### ISSUE TITLE
Enhancement request for start animation

### ISSUE THREAD

**Issue by y25zhao** [ugurethemaydin/SwiftConfettiView#2]
Hi @ugurethemaydin 
I really like your work. I am just wondering if you could enhance it so that the start animation could look like volcano eruption. (which similar to the congratulations animation from Apple's message app) Thanks

**Comment by ugurethemaydin** [comment]
Hi @y25zhao . 
Thank you for interest. Great idea. We hope in short time create new start effect features.

**Comment by oleghein** [comment]
> Hi @ugurethemaydin
> I really like your work. I am just wondering if you could enhance it so that the start animation could look like volcano eruption. (which similar to the congratulations animation from Apple's message app) Thanks

this library was ripped from this one -> https://github.com/sudeepag/SAConfettiView/issues
