### ISSUE TITLE
Type 'CAEmitterLayerEmitterShape' (aka 'NSString') has no member 'line'

### ISSUE THREAD

**Issue by mahendra-lariya** [ugurethemaydin/SwiftConfettiView#3]
Issue occur for Xcode 10.2
![Screenshot 2019-07-24 at 4 32 06 PM](https://user-images.githubusercontent.com/45392530/61788835-b59ae000-ae30-11e9-95d5-0b9867a13277.png)

**Comment by RobSwish** [comment]
I believe this is if your Swift version is less than 4.2. 

You can use `emitter.emitterShape = kCAEmitterLayerLine` instead.
