### ISSUE TITLE
Original work is not credited

### ISSUE THREAD

**Issue by lewis-smith** [ugurethemaydin/SwiftConfettiView#7]
I appreciate you taking the time to update this library, but you should def credit the original work.

Apart from bring rude and reflecting badly on you personally, this kind of behaviour really opens you up to legal action which is definitely not worth it for just adding the proper attribution.

https://github.com/sudeepag/SAConfettiView/issues/57

**Comment by zezeron** [comment]
I am referring to the project in Readme. Unfortunately, I started with SAConfettiView from this project, but SAConfettiView has not been working for years. What should I do more.

**Comment by ugurethemaydin** [comment]
I am referring to the project in Readme. Unfortunately, I started with SAConfettiView from this project, but SAConfettiView has not been working for years. What should I do more.

**Comment by m93a** [comment]
You cannot remove the name of the original author from LICENSE. The original work contains the line
```
Copyright (c) 2015 Sudeep Agarwal
```
If you don't include this line in the LICENSE file, you are commiting copyright infringement.
